# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: jhtjernsmo.Fjord
PackageVersion: 0.2.11
MinimumOSVersion: 10.0.17763.0
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/jhtjernsmo/fjord/releases/download/v0.2.11/Fjord_0.2.11_x64-setup.exe
  InstallerSha256: F91786B97B83466842C891DC16DC75F66D5C816B0538F2B43F79E481ABAB7244
  UpgradeBehavior: install
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/jhtjernsmo/fjord/releases/download/v0.2.11/Fjord_0.2.11_x64_en-US.msi
  InstallerSha256: D8453D85CC8568E0001EFE7B4CA8EC7EA0C8961F773AFA10E3C91C5CF4A8AD68
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.12.0
